// <auto-generated />
namespace Grasews.Infra.Data.EF.Postgres.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Grasews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Grasews));
        
        string IMigrationMetadata.Id
        {
            get { return "202001201753135_Grasews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
