//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grasews.Infra.CrossCutting.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grasews.Infra.CrossCutting.Email.EmailResources", typeof(EmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;!-- NAME: SIMPLE TEXT --&gt;
        ///    &lt;!--[if gte mso 15]&gt;
        ///    &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///        &lt;o:AllowPNG/&gt;
        ///        &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///    &lt;/xml&gt;
        ///    &lt;![endif]--&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewpor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailResetPassword {
            get {
                return ResourceManager.GetString("EmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;!-- NAME: SIMPLE TEXT --&gt;
        ///    &lt;!--[if gte mso 15]&gt;
        ///    &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///        &lt;o:AllowPNG/&gt;
        ///        &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///    &lt;/xml&gt;
        ///    &lt;![endif]--&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewpor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailShareInvitation {
            get {
                return ResourceManager.GetString("EmailShareInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;!-- NAME: SIMPLE TEXT --&gt;
        ///    &lt;!--[if gte mso 15]&gt;
        ///    &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///        &lt;o:AllowPNG/&gt;
        ///        &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///    &lt;/xml&gt;
        ///    &lt;![endif]--&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewpor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailShareInvitationCancelation {
            get {
                return ResourceManager.GetString("EmailShareInvitationCancelation", resourceCulture);
            }
        }
    }
}
