SELECT * FROM [USER]
SELECT * FROM [SERVICEDESCRIPTION]
SELECT * FROM [SHAREINVITATION]
SELECT * FROM [SERVICEDESCRIPTION_USER]
SELECT * FROM [GRAPHNODEPOSITION_WSDLINTERFACE]
SELECT * FROM [GRAPHNODEPOSITION_ONTOLOGYTERM]
COMMIT

--TRUNCATE TABLE [SHAREINVITATION]
--truncate table ServiceDescription_User
--delete from [User] where id <> 1
--commit