//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grasews.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grasews.Web.WebResource", typeof(WebResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Model Reference.
        /// </summary>
        public static string AddModelReference {
            get {
                return ResourceManager.GetString("AddModelReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error has happened. Please try again or contact a system administrator..
        /// </summary>
        public static string AnErrorHasHappened {
            get {
                return ResourceManager.GetString("AnErrorHasHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Ontology not found in the database..
        /// </summary>
        public static string AnErrorHasOccuredOntologyNotFoundInDatabase {
            get {
                return ResourceManager.GetString("AnErrorHasOccuredOntologyNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Service descripttion not found in the database..
        /// </summary>
        public static string AnErrorHasOccuredServiceDescriptionNotFoundInDatabase {
            get {
                return ResourceManager.GetString("AnErrorHasOccuredServiceDescriptionNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all sharing from this service description?.
        /// </summary>
        public static string AreYouSureYouWantToRemoveAllSharing {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemoveAllSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this service description sharing from this user?.
        /// </summary>
        public static string AreYouSureYouWantToRemoveSharingFromUser {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemoveSharingFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the service descriptions.
        /// </summary>
        public static string BackToTheServiceDescriptions {
            get {
                return ResourceManager.GetString("BackToTheServiceDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the system.
        /// </summary>
        public static string BackToTheSystem {
            get {
                return ResourceManager.GetString("BackToTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackLight.
        /// </summary>
        public static string BlackLight {
            get {
                return ResourceManager.GetString("BlackLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Light.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change skin.
        /// </summary>
        public static string ChangeSkin {
            get {
                return ResourceManager.GetString("ChangeSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaboration.
        /// </summary>
        public static string Collaboration {
            get {
                return ResourceManager.GetString("Collaboration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new answer.
        /// </summary>
        public static string CreateANewAnswer {
            get {
                return ResourceManager.GetString("CreateANewAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new comment.
        /// </summary>
        public static string CreateANewComment {
            get {
                return ResourceManager.GetString("CreateANewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new issue.
        /// </summary>
        public static string CreateANewIssue {
            get {
                return ResourceManager.GetString("CreateANewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new task.
        /// </summary>
        public static string CreateANewTask {
            get {
                return ResourceManager.GetString("CreateANewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an issue.
        /// </summary>
        public static string CreateAnIssue {
            get {
                return ResourceManager.GetString("CreateAnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a task.
        /// </summary>
        public static string CreateATask {
            get {
                return ResourceManager.GetString("CreateATask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new ontology.
        /// </summary>
        public static string CreateNewOntology {
            get {
                return ResourceManager.GetString("CreateNewOntology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new service description.
        /// </summary>
        public static string CreateNewServiceDescription {
            get {
                return ResourceManager.GetString("CreateNewServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph JSON.
        /// </summary>
        public static string CytoscapeGraphJson {
            get {
                return ResourceManager.GetString("CytoscapeGraphJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download WSDL.
        /// </summary>
        public static string DownloadWSDL {
            get {
                return ResourceManager.GetString("DownloadWSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail not found.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set more than you e-mail by separating them with comma..
        /// </summary>
        public static string EmailsCommaSeparated {
            get {
                return ResourceManager.GetString("EmailsCommaSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mails to share.
        /// </summary>
        public static string EmailsToShare {
            get {
                return ResourceManager.GetString("EmailsToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail to share.
        /// </summary>
        public static string EmailToShare {
            get {
                return ResourceManager.GetString("EmailToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter here your issue description.
        /// </summary>
        public static string EnterHereYourIssueDescription {
            get {
                return ResourceManager.GetString("EnterHereYourIssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter here your issue title.
        /// </summary>
        public static string EnterHereYourIssueTitle {
            get {
                return ResourceManager.GetString("EnterHereYourIssueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter here your task description.
        /// </summary>
        public static string EnterHereYourTaskDescription {
            get {
                return ResourceManager.GetString("EnterHereYourTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter here your task title.
        /// </summary>
        public static string EnterHereYourTaskTitle {
            get {
                return ResourceManager.GetString("EnterHereYourTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing users.
        /// </summary>
        public static string ExistingUsers {
            get {
                return ResourceManager.GetString("ExistingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export image.
        /// </summary>
        public static string ExportImage {
            get {
                return ResourceManager.GetString("ExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get last version of service description.
        /// </summary>
        public static string GetLastVersionOfServiceDescription {
            get {
                return ResourceManager.GetString("GetLastVersionOfServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grasews.
        /// </summary>
        public static string Grasews {
            get {
                return ResourceManager.GetString("Grasews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Light.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has SAWSDL Lifting  Schema Mapping Attribute.
        /// </summary>
        public static string HasLiftingSchemaMappingAttribute {
            get {
                return ResourceManager.GetString("HasLiftingSchemaMappingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has SAWSDL Lowering Schema Mapping Attribute.
        /// </summary>
        public static string HasLoweringSchemaMappingAttribute {
            get {
                return ResourceManager.GetString("HasLoweringSchemaMappingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has SAWSDL Model Reference Attribute.
        /// </summary>
        public static string HasModelReferenceAttribute {
            get {
                return ResourceManager.GetString("HasModelReferenceAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has SAWSDL Schema Mapping Attribute.
        /// </summary>
        public static string HasSchemaMappingAttribute {
            get {
                return ResourceManager.GetString("HasSchemaMappingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue answer created successfuly.
        /// </summary>
        public static string IssueAnswerCreatedSuccessfully {
            get {
                return ResourceManager.GetString("IssueAnswerCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue created successfuly.
        /// </summary>
        public static string IssueCreatedSuccessfuly {
            get {
                return ResourceManager.GetString("IssueCreatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue description.
        /// </summary>
        public static string IssueDescription {
            get {
                return ResourceManager.GetString("IssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue list is a group of questions related to the semantic annotation process of a service description. Every user with which a service description is shared can answer a question. However, only the user who created the issue (question) is able to mark it as solved..
        /// </summary>
        public static string IssueExplanation {
            get {
                return ResourceManager.GetString("IssueExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue failed on inserting..
        /// </summary>
        public static string IssueInsertFail {
            get {
                return ResourceManager.GetString("IssueInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue inserted with success..
        /// </summary>
        public static string IssueInsertSuccess {
            get {
                return ResourceManager.GetString("IssueInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string Issues {
            get {
                return ResourceManager.GetString("Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues created by {0}.
        /// </summary>
        public static string IssuesCreatedBy {
            get {
                return ResourceManager.GetString("IssuesCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks not solved and with answers.
        /// </summary>
        public static string IssuesNotSolvedAndWithAnswers {
            get {
                return ResourceManager.GetString("IssuesNotSolvedAndWithAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues not solved and with no answers.
        /// </summary>
        public static string IssuesNotSolvedWithNoAnswers {
            get {
                return ResourceManager.GetString("IssuesNotSolvedWithNoAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues shared with me.
        /// </summary>
        public static string IssuesSharedWithMe {
            get {
                return ResourceManager.GetString("IssuesSharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues solved.
        /// </summary>
        public static string IssuesSolved {
            get {
                return ResourceManager.GetString("IssuesSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue title.
        /// </summary>
        public static string IssueTitle {
            get {
                return ResourceManager.GetString("IssueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue updated successfully.
        /// </summary>
        public static string IssueUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("IssueUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark issue as solved.
        /// </summary>
        public static string MarkIssueAsSolved {
            get {
                return ResourceManager.GetString("MarkIssueAsSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark task as done.
        /// </summary>
        public static string MarkTaskAsDone {
            get {
                return ResourceManager.GetString("MarkTaskAsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Reference.
        /// </summary>
        public static string ModelReference {
            get {
                return ResourceManager.GetString("ModelReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My issues.
        /// </summary>
        public static string MyIssues {
            get {
                return ResourceManager.GetString("MyIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ontologies.
        /// </summary>
        public static string MyOntologies {
            get {
                return ResourceManager.GetString("MyOntologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My service descriptions.
        /// </summary>
        public static string MyServiceDescriptions {
            get {
                return ResourceManager.GetString("MyServiceDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tasks.
        /// </summary>
        public static string MyTasks {
            get {
                return ResourceManager.GetString("MyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issue for the current service description..
        /// </summary>
        public static string NoIssueForTheServiceDescription {
            get {
                return ResourceManager.GetString("NoIssueForTheServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issues have been found.
        /// </summary>
        public static string NoIssuesHaveBeenFound {
            get {
                return ResourceManager.GetString("NoIssuesHaveBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ontology in the database for the current user..
        /// </summary>
        public static string NoOntologyInDatabase {
            get {
                return ResourceManager.GetString("NoOntologyInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service descriptions in the database for the current user..
        /// </summary>
        public static string NoServiceDescriptionInDatabase {
            get {
                return ResourceManager.GetString("NoServiceDescriptionInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service descriptions shared in the database for the current user..
        /// </summary>
        public static string NoServiceDescriptionSharedInDatabase {
            get {
                return ResourceManager.GetString("NoServiceDescriptionSharedInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task for the current service description..
        /// </summary>
        public static string NoTaskForTheServiceDescription {
            get {
                return ResourceManager.GetString("NoTaskForTheServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks have been found.
        /// </summary>
        public static string NoTasksHaveBeenFound {
            get {
                return ResourceManager.GetString("NoTasksHaveBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontologies.
        /// </summary>
        public static string Ontologies {
            get {
                return ResourceManager.GetString("Ontologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontologies created by {0}.
        /// </summary>
        public static string OntologiesCreatedBy {
            get {
                return ResourceManager.GetString("OntologiesCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontologies shared with me.
        /// </summary>
        public static string OntologiesSharedWithMe {
            get {
                return ResourceManager.GetString("OntologiesSharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Ontology failed on deleting. Please try again or contact the system administrator..
        /// </summary>
        public static string OntologyDeleteFail {
            get {
                return ResourceManager.GetString("OntologyDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology deleted successfully..
        /// </summary>
        public static string OntologyDeleteSuccess {
            get {
                return ResourceManager.GetString("OntologyDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Ontology failed on inserting. Please try again or contact the system administrator..
        /// </summary>
        public static string OntologyInsertFail {
            get {
                return ResourceManager.GetString("OntologyInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology inserted successfully..
        /// </summary>
        public static string OntologyInsertSuccess {
            get {
                return ResourceManager.GetString("OntologyInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology name.
        /// </summary>
        public static string OntologyName {
            get {
                return ResourceManager.GetString("OntologyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Ontology failed on updating. Please try again or contact the system administrator..
        /// </summary>
        public static string OntologyUpdateFail {
            get {
                return ResourceManager.GetString("OntologyUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology updated successfully..
        /// </summary>
        public static string OntologyUpdateSuccess {
            get {
                return ResourceManager.GetString("OntologyUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ontology.
        /// </summary>
        public static string OpenOntology {
            get {
                return ResourceManager.GetString("OpenOntology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open OWL.
        /// </summary>
        public static string OpenOWL {
            get {
                return ResourceManager.GetString("OpenOWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open service description.
        /// </summary>
        public static string OpenServiceDescription {
            get {
                return ResourceManager.GetString("OpenServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open WSDL.
        /// </summary>
        public static string OpenWSDL {
            get {
                return ResourceManager.GetString("OpenWSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner user.
        /// </summary>
        public static string OwnerUser {
            get {
                return ResourceManager.GetString("OwnerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should not be empty..
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous answers.
        /// </summary>
        public static string PreviousAnswers {
            get {
                return ResourceManager.GetString("PreviousAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous comments.
        /// </summary>
        public static string PreviousComments {
            get {
                return ResourceManager.GetString("PreviousComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple Light.
        /// </summary>
        public static string PurpleLight {
            get {
                return ResourceManager.GetString("PurpleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Light.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh service description.
        /// </summary>
        public static string RefreshServiceDescription {
            get {
                return ResourceManager.GetString("RefreshServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all sharing.
        /// </summary>
        public static string RemoveAllSharing {
            get {
                return ResourceManager.GetString("RemoveAllSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove issue.
        /// </summary>
        public static string RemoveIssue {
            get {
                return ResourceManager.GetString("RemoveIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove sharing.
        /// </summary>
        public static string RemoveSharing {
            get {
                return ResourceManager.GetString("RemoveSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove task.
        /// </summary>
        public static string RemoveTask {
            get {
                return ResourceManager.GetString("RemoveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save WSDL.
        /// </summary>
        public static string SaveWSDL {
            get {
                return ResourceManager.GetString("SaveWSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Mapping.
        /// </summary>
        public static string SchemaMapping {
            get {
                return ResourceManager.GetString("SchemaMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Service description failed on deleting. Please try again or contact the system administrator..
        /// </summary>
        public static string ServiceDescriptionDeleteFail {
            get {
                return ResourceManager.GetString("ServiceDescriptionDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service description deleted successfully..
        /// </summary>
        public static string ServiceDescriptionDeleteSuccess {
            get {
                return ResourceManager.GetString("ServiceDescriptionDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service description element.
        /// </summary>
        public static string ServiceDescriptionElement {
            get {
                return ResourceManager.GetString("ServiceDescriptionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service description elements.
        /// </summary>
        public static string ServiceDescriptionElements {
            get {
                return ResourceManager.GetString("ServiceDescriptionElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service description element type.
        /// </summary>
        public static string ServiceDescriptionElementType {
            get {
                return ResourceManager.GetString("ServiceDescriptionElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Service description failed on inserting. Please try again or contact the system administrator..
        /// </summary>
        public static string ServiceDescriptionInsertFail {
            get {
                return ResourceManager.GetString("ServiceDescriptionInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service description inserted successfully..
        /// </summary>
        public static string ServiceDescriptionInsertSuccess {
            get {
                return ResourceManager.GetString("ServiceDescriptionInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service descriptions.
        /// </summary>
        public static string ServiceDescriptions {
            get {
                return ResourceManager.GetString("ServiceDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service descriptions created by {0}.
        /// </summary>
        public static string ServiceDescriptionsCreatedBy {
            get {
                return ResourceManager.GetString("ServiceDescriptionsCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Service description failed on sharing. Please try again or contact the system administrator..
        /// </summary>
        public static string ServiceDescriptionSharedFail {
            get {
                return ResourceManager.GetString("ServiceDescriptionSharedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service description shared successfully..
        /// </summary>
        public static string ServiceDescriptionSharedSuccess {
            get {
                return ResourceManager.GetString("ServiceDescriptionSharedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service descriptions shared with {0}.
        /// </summary>
        public static string ServiceDescriptionsSharedWith {
            get {
                return ResourceManager.GetString("ServiceDescriptionsSharedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service descriptions shared with me.
        /// </summary>
        public static string ServiceDescriptionsSharedWithMe {
            get {
                return ResourceManager.GetString("ServiceDescriptionsSharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Service description failed on updating. Please try again or contact the system administrator..
        /// </summary>
        public static string ServiceDescriptionUpdateFail {
            get {
                return ResourceManager.GetString("ServiceDescriptionUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service description updated successfully..
        /// </summary>
        public static string ServiceDescriptionUpdateSuccess {
            get {
                return ResourceManager.GetString("ServiceDescriptionUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared users.
        /// </summary>
        public static string SharedUsers {
            get {
                return ResourceManager.GetString("SharedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared users for the service description {0}.
        /// </summary>
        public static string SharedUsersForTheServiceDescription {
            get {
                return ResourceManager.GetString("SharedUsersForTheServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the service description with users.
        /// </summary>
        public static string ShareServiceDescriptionWithUsers {
            get {
                return ResourceManager.GetString("ShareServiceDescriptionWithUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share WSDL.
        /// </summary>
        public static string ShareWSDL {
            get {
                return ResourceManager.GetString("ShareWSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task comment created successfuly.
        /// </summary>
        public static string TaskCommentCreatedSuccessfuly {
            get {
                return ResourceManager.GetString("TaskCommentCreatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task created successfuly.
        /// </summary>
        public static string TaskCreatedSuccessfuly {
            get {
                return ResourceManager.GetString("TaskCreatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task description.
        /// </summary>
        public static string TaskDescription {
            get {
                return ResourceManager.GetString("TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A task list is a list of the remaining work for the semantic annotation process of a service description. Every user with which a service description is shared can make comments on a task and also they can accomplish a task by marking it as done..
        /// </summary>
        public static string TaskExplanation {
            get {
                return ResourceManager.GetString("TaskExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed on inserting..
        /// </summary>
        public static string TaskInsertFail {
            get {
                return ResourceManager.GetString("TaskInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task inserted with success..
        /// </summary>
        public static string TaskInsertSuccess {
            get {
                return ResourceManager.GetString("TaskInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks created by {0}.
        /// </summary>
        public static string TasksCreatedBy {
            get {
                return ResourceManager.GetString("TasksCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks done.
        /// </summary>
        public static string TasksDone {
            get {
                return ResourceManager.GetString("TasksDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks not done and with comments.
        /// </summary>
        public static string TasksNotDoneAndWithComments {
            get {
                return ResourceManager.GetString("TasksNotDoneAndWithComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks not done and with no comments.
        /// </summary>
        public static string TasksNotDoneWithNoComments {
            get {
                return ResourceManager.GetString("TasksNotDoneWithNoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks shared with me.
        /// </summary>
        public static string TasksSharedWithMe {
            get {
                return ResourceManager.GetString("TasksSharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task title.
        /// </summary>
        public static string TaskTitle {
            get {
                return ResourceManager.GetString("TaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task updated successfully.
        /// </summary>
        public static string TaskUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TaskUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service description is shared with no users..
        /// </summary>
        public static string ThisServiceDescriptionIsSharedWithNoUsers {
            get {
                return ResourceManager.GetString("ThisServiceDescriptionIsSharedWithNoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User image.
        /// </summary>
        public static string UserImage {
            get {
                return ResourceManager.GetString("UserImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logged user is not the owner of the requested resource..
        /// </summary>
        public static string UserIsNotTheOwner {
            get {
                return ResourceManager.GetString("UserIsNotTheOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username should not be empty..
        /// </summary>
        public static string UsernameEmpty {
            get {
                return ResourceManager.GetString("UsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password might be wrong. Please, revise and try again. Otherwise, make a new register..
        /// </summary>
        public static string UsernameOrPasswordWrong {
            get {
                return ResourceManager.GetString("UsernameOrPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View answers.
        /// </summary>
        public static string ViewAnswers {
            get {
                return ResourceManager.GetString("ViewAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View comments.
        /// </summary>
        public static string ViewComments {
            get {
                return ResourceManager.GetString("ViewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the issue list.
        /// </summary>
        public static string ViewIssueList {
            get {
                return ResourceManager.GetString("ViewIssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View my ontologies.
        /// </summary>
        public static string ViewMyOntologies {
            get {
                return ResourceManager.GetString("ViewMyOntologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View my service descriptions.
        /// </summary>
        public static string ViewMyServiceDescriptions {
            get {
                return ResourceManager.GetString("ViewMyServiceDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the task list.
        /// </summary>
        public static string ViewTaskList {
            get {
                return ResourceManager.GetString("ViewTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is an issue?.
        /// </summary>
        public static string WhatIsAnIssue {
            get {
                return ResourceManager.GetString("WhatIsAnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a task?.
        /// </summary>
        public static string WhatIsATask {
            get {
                return ResourceManager.GetString("WhatIsATask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wsdl.
        /// </summary>
        public static string Wsdl {
            get {
                return ResourceManager.GetString("Wsdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        public static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Light.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
    }
}
