//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grasews.UI.WebServiceSamples.Client.ColorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ColorService.IColorService")]
    public interface IColorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColorService/GetColors", ReplyAction="http://tempuri.org/IColorService/GetColorsResponse")]
        string[] GetColors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColorService/GetColors", ReplyAction="http://tempuri.org/IColorService/GetColorsResponse")]
        System.Threading.Tasks.Task<string[]> GetColorsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IColorServiceChannel : Grasews.UI.WebServiceSamples.Client.ColorService.IColorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColorServiceClient : System.ServiceModel.ClientBase<Grasews.UI.WebServiceSamples.Client.ColorService.IColorService>, Grasews.UI.WebServiceSamples.Client.ColorService.IColorService {
        
        public ColorServiceClient() {
        }
        
        public ColorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetColors() {
            return base.Channel.GetColors();
        }
        
        public System.Threading.Tasks.Task<string[]> GetColorsAsync() {
            return base.Channel.GetColorsAsync();
        }
    }
}
